services:
  app:
    image: 'gavrilovegor519/hh-autoupdate-resume'
    build:
      context: .
    environment: # this is example of environment variables
      - HH_AUTOUPDATE_RESUME_AUTHTOKEN=test_auth
      - HH_AUTOUPDATE_RESUME_CLIENT_ID=test_client_id
      - HH_AUTOUPDATE_RESUME_CLIENT_SECRET=test_client_secret
      - HH_AUTOUPDATE_RESUME_RESUME_ID=1
      - HH_AUTOUPDATE_RESUME_TG_BOTTOKEN=test_bot_token
      - HH_AUTOUPDATE_RESUME_TG_CHATID=test_chat_id
    networks:
      - hh-autoupdate-resume

networks:
  hh-autoupdate-resume:
    driver: bridge