services:
  app:
    image: 'gavrilovegor519/hh-autoupdate-resume'
    environment: # I'm use .env file
      - HH_AUTOUPDATE_RESUME_AUTHTOKEN=${HH_AUTOUPDATE_RESUME_AUTHTOKEN}
      - HH_AUTOUPDATE_RESUME_CLIENT_ID=${HH_AUTOUPDATE_RESUME_CLIENT_ID}
      - HH_AUTOUPDATE_RESUME_CLIENT_SECRET=${HH_AUTOUPDATE_RESUME_CLIENT_SECRET}
      - HH_AUTOUPDATE_RESUME_RESUME_ID=${HH_AUTOUPDATE_RESUME_RESUME_ID}
      - HH_AUTOUPDATE_RESUME_TG_BOTTOKEN=${HH_AUTOUPDATE_RESUME_TG_BOTTOKEN}
      - HH_AUTOUPDATE_RESUME_TG_CHATID=${HH_AUTOUPDATE_RESUME_TG_CHATID}
    restart: always
    volumes:
      - "app:/root/.java"
    networks:
      - hh-autoupdate-resume

networks:
  hh-autoupdate-resume:
    driver: bridge

volumes:
  app:
